FROM registry.suse.com/bci/golang:1.23

# Configure Go
ENV GOFLAGS=-buildvcs=false
ENV GOPATH /root/go
ENV PATH ${PATH}:/root/go/bin

ARG TERRAFORM_VERSION=1.10.4
ENV TERRAFORM_VERSION=${TERRAFORM_VERSION}

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher
ENV WORKSPACE2 ${GOPATH}/src/github.com/rancherlabs/suse-garage

WORKDIR $WORKSPACE

COPY ["./rancher", "$WORKSPACE"]
COPY ["./suse-garage", "$WORKSPACE2"]

RUN zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_15.5 snappy && zypper --gpg-auto-import-keys refresh && zypper dup --from snappy
RUN zypper refresh && zypper --non-interactive install gcc binutils glibc-devel-static ca-certificates git-core wget curl unzip tar vim less file xz gzip sed gawk iproute2 iptables jq helm
RUN zypper --non-interactive install --no-recommends openssh-clients
# && firewall-cmd --permanent --add-service=ssh && firewall-cmd --reload 
# RUN zypper install -y -f docker && rpm -e --nodeps --noscripts containerd

RUN wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"  && mv terraform /usr/local/bin
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN go mod download && \
    go install gotest.tools/gotestsum@latest

RUN cd $WORKSPACE2/rancher-local/k3s-ha && chmod 777 e2e_create_rancher.sh install_rancher_on_cluster.sh ips_from_terraform.sh create_k3s_server.sh .remote_script.sh

RUN chmod -R 600 $WORKSPACE/tests/v2/validation/.ssh/