FROM registry.suse.com/bci/golang:1.23

# Configure Go
ENV GOFLAGS=-buildvcs=false
ENV GOPATH /root/go
ENV PATH ${PATH}:/root/go/bin

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher
# ENV WORKSPACE2 ${GOPATH}/src/github.com/rancherlabs/suse-garage

WORKDIR $WORKSPACE

COPY ["./rancher", "$WORKSPACE"]
# COPY ["./suse-garage", "$WORKSPACE2"]


RUN zypper -n install gcc binutils glibc-devel-static ca-certificates git-core wget curl unzip tar vim less file xz gzip sed gawk iproute2 iptables jq helm
RUN zypper install -y -f docker && rpm -e --nodeps --noscripts containerd
RUN go mod download && \
    go install gotest.tools/gotestsum@latest

# RUN cd suse-garage && chmod 777 e2e_create_rancher.sh insall_rancher_on_cluster.sh ips_from_terraform.sh create_k3s_server.sh
# necessary to run if statements using [[ ]]
SHELL ["/bin/bash", "-c"] 

ARG RKE_VERSION
RUN if [[ -n "$RKE_VERSION" ]] ; then echo installing latest version RKE && \
    curl -0Ls https://github.com/rancher/rke/releases/latest/download/rke_linux-amd64 > rke ; else echo installing ${RKE_VERSION} version RKE && \
    curl -0Ls https://github.com/rancher/rke/releases/download/$RKE_VERSION/rke_linux-amd64 > rke; fi;
RUN mv rke /bin/rke && \
    chmod +x /bin/rke

ARG CLI_VERSION
RUN if [[ -n "$CLI_VERSION" ]] ; then  \
        echo installing CLI version $CLI_VERSION ; \
        curl -LO https://github.com/rancher/cli/releases/download/$CLI_VERSION/rancher-linux-amd64-$CLI_VERSION.tar.gz ; \
        tar -xf rancher-linux-amd64-$CLI_VERSION.tar.gz && \
        mv rancher-$CLI_VERSION/rancher /bin/rancher && \
        chmod +x /bin/rancher; fi;